# permissions for end users to view operatortesters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatortester-viewer-role
rules:
- apiGroups:
  - demo.jackzhang.io
  resources:
  - operatortesters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.jackzhang.io
  resources:
  - operatortesters/status
  verbs:
  - get
