# permissions for end users to edit operatortesters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatortester-editor-role
rules:
- apiGroups:
  - demo.jackzhang.io
  resources:
  - operatortesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.jackzhang.io
  resources:
  - operatortesters/status
  verbs:
  - get
